[basic]
zone = "default"
service = "sparta_backend"
apiport = 8000
apiroot = "/api"
inswarm = false
dynamicconfig = false
prof = false
devmode = false

[log]
level = "DEBUG"
path = ""
graylog = ""
fields = ""

[service]
data_dir = "./data"
root_dir = "./workspace"
sparta_python_tools = "/home/sparta/tools/pizza" # export SPARTA_PYTHON_TOOLS=/home/sparta/tools/pizza
exec_dir = "/home/sparta/tools"
