[basic]
zone = "default"
service = "sparta_backend"
apiport = 8000
apiroot = "/api"
inswarm = false
dynamicconfig = false
prof = false
devmode = false

[log]
level = "DEBUG"
path = ""
graylog = ""
fields = ""

[service]
data_dir = "./data"
