[basic]
zone = "default"
service = "sparta_backend"
apiport = 8000
apiroot = "/api"
inswarm = false
dynamicconfig = false
prof = false
devmode = false

[log]
level = "INFO"
path = ""
graylog = ""
fields = ""

[service]
data_dir = "/home/workspace/project/sparta_backend/data" 
root_dir = "/home/workspace/project/sparta_backend"
sparta_python_tools = "/home/workspace/project/sparta_backend/sparta/pizza" # export SPARTA_PYTHON_TOOLS=/home/sparta/tools/pizza
script_dir = "/home/workspace/project/sparta_backend/sparta"
spa_exec = "/home/workspace/project/sparta_backend/bin/spa_"
